name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, x64]

    env:
      DOCKER_REGISTRY: harbor.test.myfaccloud-301.com
      DOCKER_PROJECT: demogitops
      APP_NAME: simple-app
      IMAGE_TAG: latest  # Optional: use ${{ github.sha }} for unique tags
      GITOPS_REPO: chunji08/SIMPLEDEMO-GITOPS  # Use {owner}/{repo} format
      GITOPS_BRANCH: main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login https://${{ env.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_PROJECT }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker Image to Harbor
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_PROJECT }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}

      - name: Checkout GitOps Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITOPS_REPO }}  # Use {owner}/{repo} format
          ref: ${{ env.GITOPS_BRANCH }}
          path: gitops
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Image Tag in Kubernetes Manifests
        run: |
          cd gitops
          sed -i 's|image: .*/simple-app:.*|image: ${DOCKER_REGISTRY}/${DOCKER_PROJECT}/${APP_NAME}:${IMAGE_TAG}|' deployment.yaml
          git config user.name "${{ secrets.GIT_USERNAME }}"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -am "Update image tag to ${{ env.IMAGE_TAG }}"
          echo ${{ secrets.GIT_USERNAME }}
          echo ${{ secrets.GIT_PASSWORD }}
          echo ${{ env.GITOPS_BRANCH}}
          git push https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/chunji08/SIMPLEDEMO-GITOPS.git ${{ env.GITOPS_BRANCH }}
